[package]
name = "aoc2015"
version = "0.1.0"
authors = ["Alexandre <email@email.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
fancy-regex = "0.4.1"
